[env]
platform = symlink:///home/rar/dev/libretiny
framework = arduino
platform_packages =
	library-wfx-fmac-driver @ symlink:///home/rar/dev/framework-wfx-fmac-driver

[env:juicebox]
board = wgm160p-juicebox-40
