#pragma once

#define ASSERT_HALT					  1
#define ASSERT_IGNORE				  2
#define ASSERT_REBOOT				  3
#define AT_SERVICE_CFG				  0
#define BLE_DEFAULT_WIFI_REQUEST	  2
#define BLE_VERSION_4_2				  1
#define BLE_VERSION_5_x				  2
#define BLE_WIFI_CO_REQUEST			  3
#define CFG_AIRKISS_TEST			  0
#define CFG_AP_MONITOR_COEXIST		  0
#define CFG_AP_SUPPORT_HT_IE		  0
#define CFG_ASSERT_OPTION			  ASSERT_IGNORE
#define CFG_BACKGROUND_PRINT		  0
#define CFG_BK_AWARE				  0
#define CFG_BK_AWARE_OUI			  "\xC8\x47\x8C"
#define CFG_BLE_ADV_NUM				  1
#define CFG_BLE_CONN_NUM			  1
#define CFG_BLE_INIT_NUM			  0
#define CFG_BLE_SCAN_NUM			  1
#define CFG_BLE_VERSION				  BLE_VERSION_5_x
#define CFG_EASY_FLASH				  0
#define CFG_ENABLE_BUTTON			  0
#define CFG_ENABLE_DEMO_TEST		  0
#define CFG_ENABLE_WPA_LOG			  0
#define CFG_GENERAL_DMA				  1
#define CFG_IEEE80211N				  1
#define CFG_IEEE80211W				  0
#define CFG_INT_WDG_ENABLED			  0
#define CFG_INT_WDG_PERIOD_MS		  10000
#define CFG_IPERF_TEST				  0
#define CFG_JTAG_ENABLE				  0
#define CFG_LESS_MEMERY_IN_RWNX		  0
#define CFG_LWIP_MEM_POLICY			  LWIP_REDUCE_THE_PLAN
#define CFG_MAC_PHY_BAPASS			  1
#define CFG_MSDU_RESV_HEAD_LEN		  96
#define CFG_MSDU_RESV_TAIL_LEN		  16
#define CFG_PERIPHERAL_TEST			  0
#define CFG_REAL_SDIO				  0
#define CFG_RELEASE_FIRMWARE		  0
#define CFG_ROLE_LAUNCH				  0
#define CFG_RUNNING_PLATFORM		  SOC_PLATFORM
#define CFG_RWNX_QOS_MSDU			  1
#define CFG_RX_SENSITIVITY_TEST		  1
#define CFG_SARADC_CALIBRATE		  0
#define CFG_SDIO					  0
#define CFG_SDIO_TRANS				  0
#define CFG_SOC_NAME				  SOC_BK7231N
#define CFG_SUPPOET_BSSID_CONNECT	  0
#define CFG_SUPPORT_BKREG			  1
#define CFG_SUPPORT_BLE				  1
#define CFG_SUPPORT_BLE_MESH		  0
#define CFG_SUPPORT_BSSID_CONNECT	  0
#define CFG_SUPPORT_CALIBRATION		  1
#define CFG_SUPPORT_MANUAL_CALI		  1
#define CFG_SUPPORT_OTA_HTTP		  1
#define CFG_SUPPORT_OTA_TFTP		  0
#define CFG_SUPPORT_SPI_TEST		  0
#define CFG_SUPPORT_TIANZHIHENG_DRONE 0
#define CFG_SUPPORT_TPC_PA_MAP		  1
#define CFG_SYS_REDUCE_NORMAL_POWER	  0
#define CFG_TASK_WDG_ENABLED		  0
#define CFG_TASK_WDG_PERIOD_MS		  60000
#define CFG_TCP_SERVER_TEST			  0
#define CFG_TX_EVM_TEST				  1
#define CFG_UART_DEBUG				  0
#define CFG_UART_DEBUG_COMMAND_LINE	  1
#define CFG_UDISK_MP3				  0
#define CFG_USB						  0
#define CFG_USE_AP_IDLE				  0
#define CFG_USE_AP_PS				  0
#define CFG_USE_AUD_ADC				  0
#define CFG_USE_AUD_DAC				  0
#define CFG_USE_AUDIO				  0
#define CFG_USE_BLE_PS				  1
#define CFG_USE_CAMERA_INTF			  0
#define CFG_USE_DEEP_PS				  1
#define CFG_USE_DHCP				  1
#define CFG_USE_FAKERTC_PS			  0
#define CFG_USE_FTPD_UPGRADE		  0
#define CFG_USE_I2C1				  0
#define CFG_USE_I2C2				  1
#define CFG_USE_LWIP_NETSTACK		  1
#define CFG_USE_MCU_PS				  1
#define CFG_USE_PTA					  0
#define CFG_USE_SDCARD_HOST			  0
#define CFG_USE_SPI_DMA				  1
#define CFG_USE_SPI_MASTER			  1
#define CFG_USE_SPI_SLAVE			  1
#define CFG_USE_SPIDMA				  0
#define CFG_USE_STA_PS				  1
#define CFG_USE_TEMPERATURE_DETECT	  0
#define CFG_USE_TICK_CAL			  1
#define CFG_USE_UART1				  1
#define CFG_USE_USB_CHARGE			  0
#define CFG_USE_USB_HOST			  0
#define CFG_USE_WPA_29				  1
#define CFG_WFA_CERT				  0
#define CFG_WIFI_RAW_TX_CMD			  0
#define CFG_WIFI_SENSOR				  0
#define CFG_WLAN_FAST_CONNECT		  0
#define CFG_WPA_CTRL_IFACE			  1
#define CFG_WPA3					  0
#define CFG_XTAL_FREQUENCE			  CFG_XTAL_FREQUENCE_26M
#define CFG_XTAL_FREQUENCE_26M		  26000000
#define CFG_XTAL_FREQUENCE_40M		  40000000
#define CONFIG_APP_MP3PLAYER		  0
#define FPGA_PLATFORM				  0
#define LWIP_DEFAULT_MEM_POLICY		  1
#define LWIP_REDUCE_THE_PLAN		  2
#define OSMALLOC_STATISTICAL		  0
#define RF_USE_POLICY				  WIFI_DEFAULT_BLE_REQUEST
#define SOC_BK7221U					  3
#define SOC_BK7231					  1
#define SOC_BK7231N					  5
#define SOC_BK7231U					  2
#define SOC_BK7271					  4
#define SOC_PLATFORM				  1
#define THD_APPLICATION_PRIORITY	  3
#define THD_CORE_PRIORITY			  2
#define THD_EXTENDED_APP_PRIORITY	  5
#define THD_HOSTAPD_PRIORITY		  5
#define THD_INIT_PRIORITY			  4
#define THD_LWIP_PRIORITY			  4
#define THD_MEDIA_PRIORITY			  4
#define THD_RECONNECT_PRIORITY		  4
#define THD_UBG_PRIORITY			  5
#define THD_UMP3_PRIORITY			  4
#define THD_WPAS_PRIORITY			  5
#define THDD_KEY_SCAN_PRIORITY		  7
#define UART1_USE_FIFO_REC			  0
#define UART2_USE_FIFO_REC			  0
#define WIFI_DEFAULT_BLE_REQUEST	  1
