name: Push (master)
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install docs dependencies
        run: pip install -U ltchiptool "boardgen>=0.11.0"

      - name: Generate docs and static JSON files
        run: |
          mkdir -p site/
          boardgen ltci
          python docs/scripts/write_boards.py
          python docs/scripts/write_apis.py
          python docs/scripts/prepare_doxygen.py
          python docs/scripts/build_json.py
          cp *.json site/

      - name: Set custom domain
        run: |
          mkdir -p site/
          echo docs.libretiny.eu > site/CNAME

      - name: Deploy docs
        uses: libretiny-eu/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base doxygen
          REQUIREMENTS: docs/requirements.txt
          CUSTOM_DOMAIN: docs.libretiny.eu
