name: Push (dev), Pull Request
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
jobs:
  lint-clang:
    name: Run Clang lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-clang.yml@master
  lint-python:
    name: Run Python lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-python.yml@master
